"""
Django settings for inge4 project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [os.getenv('APPLICATION_URL'), os.getenv('POD_IP')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inge4',
    'signing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'inge4.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [f'{BASE_DIR}/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inge4.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DEFAULT_POSTGRES_DATABASE_NAME'),
        'USER': os.getenv('DEFAULT_POSTGRES_USER'),
        'PASSWORD': os.getenv('DEFAULT_POSTGRES_PASSWORD'),
        'HOST': os.getenv('DEFAULT_POSTGRES_HOST'),
        'PORT': os.getenv('DEFAULT_POSTGRES_PORT', "5432"),
        'OPTIONS': {
            'sslmode': 'verify-full',
            'sslrootcert': '/home/{user}/.postgresql/default_root.crt',
            'sslcert': '/home/{user}/.postgresql/default.crt',
            'sslkey': '/home/{user}/.postgresql/default.key',
        },
    },
    # RIVM Vaccination registration
    'vcbe_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('VCBE_DB_POSTGRES_DATABASE_NAME'),
        'USER': os.getenv('VCBE_DB_POSTGRES_USER'),
        'PASSWORD': os.getenv('VCBE_DB_POSTGRES_PASSWORD'),
        'HOST': os.getenv('VCBE_DB_POSTGRES_HOST'),
        'PORT': os.getenv('VCBE_DB_POSTGRES_PORT', "5432"),
        'OPTIONS': {
            'sslmode': 'verify-full',
            'sslrootcert': '/home/{user}/.postgresql/default_root.crt',
            'sslcert': '/home/{user}/.postgresql/default.crt',
            'sslkey': '/home/{user}/.postgresql/default.key',
        },
    },
}

DATABASE_ROUTERS = ['signing.database_routers.vcbe_db.VCBEDatabaseRouter']

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

NACL_FIELDS_KEY = open('signing/secrets/vcbe_db_nacl_fields.key', 'rb').read()
